import HeaderNav from "@/components/layout/HeaderNav";
import Footer from "@/components/layout/Footer";
import "./globals.css";
import StickyHeader from "@/components/layout/StickyHeader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className="relative">
        <HeaderNav />
        <StickyHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
